// <auto-generated />
using System;
using LibrarySystem.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LibrarySystem.Migrations
{
    [DbContext(typeof(LibrarySystemContext))]
    partial class LibrarySystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LibrarySystem.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "John Travolta",
                            Isbn = "12312123132",
                            Title = "Sun is shining"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Angelina Jolie",
                            Isbn = "342545667765",
                            Title = "Master that game"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Larry Clint",
                            Isbn = "756324vddsffd",
                            Title = "Stop sending SMS"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Haskel Peanut",
                            Isbn = "12312123132",
                            Title = "I like peanutbutter"
                        });
                });

            modelBuilder.Entity("LibrarySystem.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("123e4567-e89b-12d3-a456-426655440000"),
                            FullName = "Andrzej Duda"
                        },
                        new
                        {
                            Id = new Guid("123e5432-e89b-12d3-a456-426655440000"),
                            FullName = "Barack Obama"
                        },
                        new
                        {
                            Id = new Guid("213e4567-e89b-12d3-a456-426655440000"),
                            FullName = "Tristan Burba"
                        });
                });

            modelBuilder.Entity("LibrarySystem.Entities.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Rental");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 2,
                            CustomerId = new Guid("123e4567-e89b-12d3-a456-426655440000"),
                            StartDate = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BookId = 4,
                            CustomerId = new Guid("213e4567-e89b-12d3-a456-426655440000"),
                            EndDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("LibrarySystem.Entities.Rental", b =>
                {
                    b.HasOne("LibrarySystem.Entities.Book", "Book")
                        .WithMany("Rental")
                        .HasForeignKey("BookId")
                        .HasConstraintName("FK__Rental__BookId__5CD6CB2B")
                        .IsRequired();

                    b.HasOne("LibrarySystem.Entities.Customer", "Customer")
                        .WithMany("Rental")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK__Rental__Customer__5BE2A6F2")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
